### ISSUE TITLE
global listeners for laptop keyboard 

### ISSUE THREAD

**Issue by ghost** [hybridgroup/artoo-keyboard#6]
Hello, I am trying to create a global keyboard-macros program on my personal laptop.

This is Ubuntu 14.04 on a HP EliteBook2540p running Ruby 2.4.0-dev

Currently I have artoo-keyboard working for text that is typed directly into the terminal where the script is running.

I'm trying to have global listeners (so the terminal doesnt have to be in focus).

I've tried specifying the keyboard port using the following:

`connection :keyboard, adaptor: :keyboard, port: '/devices/platform/i8042/serio0/input/input3'`

I got this port number by running `cat /proc/bus/input/devices`. 

I noticed that if I also include `device :keyboard, driver: :keyboard, connection: :keyboard`, then the above "connection" call using port has no effect. So I've removed it.

When I try running the script, I get the following trace:

``` txt
I, [2016-02-27T16:20:01.810087 #3607]  INFO -- : Registering connection 'keyboard'...
I, [2016-02-27T16:20:01.810222 #3607]  INFO -- : Preparing work...
I, [2016-02-27T16:20:01.811240 #3607]  INFO -- : Initializing artoo::connection keyboard...
I, [2016-02-27T16:20:01.819236 #3607]  INFO -- : Starting work...
I, [2016-02-27T16:20:01.819592 #3607]  INFO -- : Connecting to 'keyboard' on port '/devices/platform/i8042/serio0/input/input3'...
E, [2016-02-27T16:20:01.823406 #3607] ERROR -- : Actor crashed!
                                                               NoMethodError: undefined method `name' for "Unknown Command":String
                                                    /home/max/.rbenv/versions/2.4.0-dev/lib/ruby/gems/2.4.0/gems/artoo-1.8.2/lib/artoo/events.rb:10:in `block in on'

```

I've also tried running the program with `sudo` but it has the same output. 

I'm new to all this hardware business, so I would appreciate knowing if I'm obviously making a mistake somewhere or if my approach is wrong in a serious way. 

Thanks

**Comment by deadprogram** [comment]
Hi, @MaxPleaner there is not any current ability for Artoo to listen for keyboard events outside of a terminal window. That would require additional coding beyond what it currently handles. A PR that added this would be happily accepted! :)

**Comment by ghost** [comment]
Hey Ron, thanks for this response. I have no idea how to begin doing this.
If you have any advice for how a solution could be pieced together, I
suppose I might be able to try.

**Comment by deadprogram** [comment]
Capturing global keyboard events outside of a window focus in a cross-platform way is not going to be easy, I can tell you that...

**Comment by ghost** [comment]
On a Linux platform, it looks like it can be done with `evtest`. I might put
something together using this, but that approach no longer uses
`artoo-keyboard`, so i'm fine closing this issue. Thanks for the
code, by the way.
